### PR TITLE
✨ Added loader while fetching issue and fixed bugs

### PR DESCRIPTION
**Pull request by max-programming**

### CODE REVIEW

**Comment by max-programming** [comment]
@harshhhdev Please let me know the logs on Vercel so I can work on them

**Comment by harshhhdev** [comment]
> @harshhhdev Please let me know the logs on Vercel so I can work on them

Yup. I found out the error.

Basically, in components/Search/Search.tsx:

```tsx
      {loading ? (
        !error && !tags && <IssueLoader />
      ) : (
        <Issue
          title={title!}
          date={date!}
          author={author!}
          authorURL={authorLink!}
          link={link!}
          number={number!}
          labels={tags!}
        />
      )}
```

Here you load the Issue component, but currently all the fields are null. Vercel was throwing an error for this.

**Comment by harshhhdev** [comment]
Hey,

It's been a while. If you don't mind, can I just merge this PR & make the changes myself? The loading bar is kinda something I'd like to have, & I'm fine with making the changes to it myself.

**Comment by max-programming** [comment]
Sure @harshhhdev! As of now, because of academics, I am not able to work on anything. Go for it 👍

**Pull request merged**
